### PR TITLE
#3 Added Labels to Zoom and Volume Slider

### LINKED ISSUE #3: ⚡️Add Labels to Zoom and Volume Sliders
⚡️Add Labels to _Zoom_ and _Volume_ Sliders
---

The sliders don't visibly explain their purpose, and hence need labels on them.
Add a _Zoom_ label under Slider 1.
Add a _Volume_ label under Slider 2.

### PR DESCRIPTION
**Pull request by SahilSingh177**
Fixes #3 

Screenshot (142)

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
As Mentioned in the Issue itself, the Lables _Zoom_ and _Volume_ would be better suited under the Sliders, than in the side. Kindly look into that.

**Comment by SahilSingh177** [comment]
Ok sir.

**Comment by SahilSingh177** [comment]
Fixed #3 

Added labels under the sliders
Screenshot (148)

**Comment by PrerakMathur20** [comment]
LGTM!

**Pull request merged**
