### PR TITLE
Added the SETUP section in README.md file

### LINKED ISSUE #2: 🗞 Add Setup section to README.md file
📄 Add Setup section to README.md file
---

To allow easy setup of the project, create a **Setup** section in the `README.md` file and add steps on how locally allow the setup of the project.

The _Setup_ Section must include the following -

* Create a Fork
* `git clone` the project
* Check for Prerequisites for the project
* Commands for Initiating and running the project

### PR DESCRIPTION
**Pull request by KanishkDadhich**
Hey @PrerakMathur20 . I've made a new PR as earlier one was having some issues of reset as mentioned in the previous PR (which is closed now).
The issue is fixed now.
FIXES #2 
Here are some screenshots of the changes made in the README.md.
Please refer.
Screenshot of README md

Thanks :)

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
@KanishkDadhich Kindly take a look at the code reviews and fix them!

**Comment by KanishkDadhich** [comment]
Hey @PrerakMathur20. I've gone through the issue requirements and my changes in README.md file (Added the SETUP section) but I'm not able to figure out exactly what needs to be fixed. According to my knowledge, the setup section is correct, but if it isn't then could you please tell me what exactly needs to fixed?

Issue #2 
Thanks :)

**Comment by PrerakMathur20** [comment]
As mentioned in the review above,

https://github.com/KanishkDadhich/geet-hub-editor/blob/5d1c655d41cd56bba0524842c5819fdcae8297de/README.md?plain=1#L35

Here, It would be better with `git clone https://github.com/<YOUR USERNAME>/geet-hub-editor.git` here, since there is no point in cloning the **IITL's** repository for the purpose of contributing.

Also,

https://github.com/KanishkDadhich/geet-hub-editor/blob/5d1c655d41cd56bba0524842c5819fdcae8297de/README.md?plain=1#L91

Here, `git add .` is slightly misleading as usually we only intend to push the files which are required and not all the files which have been changed.

**Comment by KanishkDadhich** [comment]
Hello @PrerakMathur20 . 
I've made the changes according to the code reviews and fixed them . FIXES #2 
I've corrected the git clone command to `git clone https://github.com/<YOUR USERNAME>/geet-hub-editor.git` and also corrected the `git add . ` command.

Here are the screenshots of the changes made :-
image
image

I hope this helps
Thankyou for the code reviews :)

**Comment by PrerakMathur20** [comment]
LGTM!
Also, You need not mention the Issue in each comment, just the Primary Description of the PR 😊

**Pull request merged**
