### PR TITLE
Added the SETUP section in README.md file

### LINKED ISSUE #2: 🗞 Add Setup section to README.md file
📄 Add Setup section to README.md file
---

To allow easy setup of the project, create a **Setup** section in the `README.md` file and add steps on how locally allow the setup of the project.

The _Setup_ Section must include the following -

* Create a Fork
* `git clone` the project
* Check for Prerequisites for the project
* Commands for Initiating and running the project

### PR DESCRIPTION
**Pull request by KanishkDadhich**
Hey @PrerakMathur20 .
FIXES #2 
I've added the SETUP section in the README.md file as per the requirements mentioned in the issue.
Please refer.

Here are some screenshots of the changes made in the README.md file
Screenshot of README md

Thanks :)

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
Looks good, but kindly revert any and all changes you've made to any file except for the `README.md` file.

**Comment by KanishkDadhich** [comment]
Sure.

**Comment by KanishkDadhich** [comment]
Hey @PrerakMathur20 . Actually I'm facing a small issue regarding it.
I've forked this repo on my Github. 
Then I cloned it and made changes.
I've also run the command to revert the commit (i.e git checkout [commit id] -- path/to/file)
The command ran successfully.
And then I pushed the changes (git push)
But I'm confused that all the changes are reverted or not.
Can you help?

**Comment by PrerakMathur20** [comment]
@KanishkDadhich 
If you can't see your commit message in the PR, it probably means, either your git push failed or you've made a commit somewhere else.
As you can see above, your old commit message is visible "`Added the SETUP section in README.md`", but after that no new commit messages are visible. 

I recommend you to re-clone your fork and `git pull` the changes you've made on the `main` branch. 

After that, take a look here, [Remove Files From Git Commit](https://devconnected.com/how-to-remove-files-from-git-commit/).

**Comment by KanishkDadhich** [comment]
Thankyou sir. I tried using these commands. But unfortunately I wasn't able to reset the changes in the files other than README.md. And the reason I think is that yesterday I've already pushed the the changes using (git pull) . And while watching some videos regarding git reset command , they were performing this command after they have committed and before they have pushed the changes to github. 

Hence to avoid confusion I'm making a new PR which will contain changes only in the README.md.
Is that okay sir?
Sorry for the inconvenience caused.

**Comment by PrerakMathur20** [comment]
Sure. No issues.

**Pull request closed without merging**
